--- #YAML:1.0
name:                WWW-TV
version:             0.13
abstract:            Parse TV.com for information about TV shows.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    LWP::UserAgent:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Danial Pearce <cpan@tigris.id.au>
